### ISSUE TITLE
Villager suffocation

### ISSUE THREAD

**Issue by TheAwesomeGem** [WildBamaBoy/minecraft-comes-alive#463]
All of my villagers are suffocating into walls and villager beds. I believe it to be a game-breaking bug.

I am using the version "MCA-5.0.6-1.7.10-universal".

**Comment by Hernan0708** [comment]
yes. i got so mad when i mad when my spouse died. i decided to downgrade. i almost felt like rage quitting.... -_- 


btw i remember in MCA 4.1.5 that it can detect an area that will prevent the villagers from sufficating or interfering with nearby blocks.

**Comment by TheAwesomeGem** [comment]
Thanks for replying Hernan0708. Which version do you recommend is the most stable?

**Comment by TheShootingStar45** [comment]
@TheAwesomeGem @Hernan0708 Well, i have been reviewing other issues and, i'm still trying on the latest update for minecraft 1.7.10, MCA 5.0.6.1. Many bug has been resolved, but i haven't see any issue, but one thing that your child may suffocate too if you picked up your child in a low-ceiling building or a gap. (That's not an issue by the way, but it would be great if WIldBamaBoy making child resist to suffocate while picked up due to our protection to him/her =) )

I know one thing if your spouse suffocate into beds, they won't die. But i don't know about the wall. Anyone knows?

I was thinking, however if we stay on the same version and downgrading wouldn't too much helping us, so i recommend playing on the latest update, "MCA 5.0.6.1 for Minecraft 1.7.10" because many bug have been fixed =)
Anyone would give their other MCA version recommendation?

**Comment by TheAwesomeGem** [comment]
@TheShootingStar45 It is really strange that I cannot reproduce the bug. The only way I know they died by suffocating is from the help of the gravestone mod. If it helps, it's an underground vault and it seems they somehow glitch into the walls and take suffocation damage by being pushed  or pathfinding into walls.

**Comment by Hernan0708** [comment]
@TheAwesomeGem I Recommend MCA 4.1.5

but you must start a new world :/

**Comment by WildBamaBoy** [comment]
Fixed in f23dc922d70fb2c3d198e1f24b89faf62cf751d9

**Comment by SlimePuncher** [comment]
Nope, still happening
Saved and quit to title, returned the next day to see a villager stuck in the wall suffocating.
